-- Add calculator formula fields to products
ALTER TABLE products ADD COLUMN IF NOT EXISTS coverage_per_box NUMERIC(10,4) DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS pieces_per_box INTEGER DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS plank_width NUMERIC(10,2) DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS plank_length NUMERIC(10,2) DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS waste_percentage NUMERIC(5,2) DEFAULT 5;
